language: php

php: 
  - 5.3
  - 5.4

services:
  - redis-server

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - phpenv config-add apc.ini

script: phpunit